
services:
  app:
    build: .
    container_name: gotyolo
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=database
      - DB_USER=root
      - DB_PASSWORD=rootadmin
      - DB_NAME=gotyolo
      - NODE_ENV=production
    depends_on:
      - database
  
  database:
    image: mysql:8.0
    container_name: gotyolo_db
    environment:
      MYSQL_ROOT_PASSWORD: rootadmin
      MYSQL_DATABASE: gotyolo
    volumes:
      - data:/var/lib/mysql
    ports:
      - "3306:3306"
      
volumes:
  data: